"Resource/UI/StampDonationAdd.res"
{
	"ConfirmDialog"
	{
		"ControlName"		"Frame"
		"fieldName"		"ConfirmDialog"
		"xpos"			"c-150"
		"ypos"			"90"
		"wide"			"450"
		"tall"			"260"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"settitlebarvisible"	"0"
		"PaintBackgroundType"	"0"
	}
	
	"TitleLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"TitleLabel"
		"font"			"HudFontMediumBold"
		"labelText"		"#ConfirmTitle"
		"textAlignment"	"north"
		"xpos"			"0"
		"ypos"			"15"
		"zpos"			"1"
		"wide"			"450"
		"tall"			"30"
		"autoResize"	"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
	}
	
	"ExplanationLabel"
	{
		"font"			"Size 40"
		"labelText"		"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"		// Adjusting this increases/decreases the size of the whole element
		"textAlignment"	"north-west"
		"xpos"			"r-6969"																// Prevents text from drawing
		"ypos"			"25"																	// Adjusting this moves the buttons' ypos (??)
	}
	
	"bh_ExplanationLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"			"bh_ExplanationLabel"
		"font"				"Size 16"
		"labelText"			"%text%"
		"textAlignment"		"north-west"
		"xpos"				"0"
		"ypos"				"50"
		"zpos"				"1"
		"wide"				"450"
		"tall"				"50"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"wrap"				"1"
		"centerwrap"		"1"
}

	"ExplanationLabel2"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ExplanationLabel2"
		"font"			"Size 12"
		"labelText"		"#Store_ConfirmStampDonationAddText2"
		"textAlignment"	"north-west"
		"xpos"			"0"
		"ypos"			"102"
		"zpos"			"1"
		"wide"			"450"
		"tall"			"170"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"wrap"			"1"
		"centerwrap"	"1"
		"fgcolor_override" "200 80 60 255"
	}

	"ItemImagePanel"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ItemImagePanel"
		"xpos"			"282"
		"ypos"			"45"
		"wide"			"150"
		"tall"			"150"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"scaleImage"		"1"
	}

	"ItemImagePanel2"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ItemImagePanel2"
		"xpos"			"155"
		"ypos"			"150"
		"wide"			"140"
		"tall"			"140"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"scaleImage"		"1"
	}

	"Nope"
	{
		"ControlName"	"CExButton"
		"fieldName"		"Nope"
		"xpos"			"5"
		"ypos"			"235"
		"zpos"			"20"
		"wide"			"100"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"0"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#Store_Nope"
		"font"			"Size 11"
		"textAlignment"	"center"
		"textinsetx"	"50"
		"dulltext"		"0"
		"brighttext"	"0"
		"Command"		"nope"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		
		"AllCaps"			"1"
		"border_default"	"ButtonDefault"
		"border_armed"		"ButtonHover"
		"paintborder"		"1"
		"paintbackground"	"0"
	}			

	"ConfirmButton"
	{
		"ControlName"	"CExButton"
		"fieldName"		"ConfirmButton"
		"xpos"			"345"
		"ypos"			"235"
		"zpos"			"20"
		"wide"			"100"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"%price%"
		"font"			"Size 11"
		"textAlignment"	"center"
		"textinsetx"	"50"
		"dulltext"		"0"
		"brighttext"	"0"
		"Command"		"add_stamp_to_cart"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/vote_success.wav"
		
		"AllCaps"			"1"
		"border_default"	"ButtonDefault"
		"border_armed"		"ButtonHover"
		"paintborder"		"1"
		"paintbackground"	"0"
	}

	"PriceLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"PriceLabel"
		"font"			"HudFontSmallBold"
		"labelText"		"%price%"
		"textAlignment"	"north-east"
		"xpos"			"345"
		"ypos"			"195"
		"zpos"			"25"
		"wide"			"100"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"centerwrap"	"1"
		"fgcolor_override" "121 195 58 255"
	}
}
